FROM docker.n8n.io/n8nio/n8n:2.0.0

USER root

RUN apk add --no-cache \
  python3 py3-pip py3-virtualenv \
  build-base gcc musl-dev libffi-dev openssl-dev
ENV PATH="/home/keerthi/Dev/ai/n8n-automation-master/.venv/bin:$PATH"

USER node
